dist: trusty
sudo: false

#travis configuration for coverage testing
language: cpp

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      clang-11

script:
  cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CROSSCOMPILING=1 -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0
