name: clang CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clang 12 and libc++
      id: install_clang_12
      shell: bash
      working-directory: ${{ env.HOME }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 12
        sudo apt-get install libc++-12-dev libc++abi-12-dev
        ls

    - name: CLANG check
      run: clang++-12 -v

    - name: Build clang
      working-directory: ${{ env.HOME }}
      shell: bash
      run: |
           cmake . -DCMAKE_BUILD_TYPE=Release  
           make
           ls
           cd doc
           ls
           cd doc_doxygen 
           ls
           cd html 
           ls
      env:
        CXX: clang++-12
        CC: clang-12         
           
    - name: Benchmark
      working-directory: ${{ env.HOME }}
      shell: bash
      continue-on-error: true
      run: ./benchmark_eswitch

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: doc/doc_doxygen/html # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
    # - name: Deploy Docs
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     # Default Doxyfile build documentation to html directory. 
    #     # Change the directory if changes in Doxyfile
    #     publish_dir: ./doc/doc_doxygen/html
    #     run: |
    #          ls
    #          cd doc
    #          ls
    #          cd doc_doxygen 
    #          ls
    #          cd html 
    #          ls

