name: clang CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clang 11 and libc++
      id: install_clang_11
      shell: bash
      working-directory: ${{ env.HOME }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 11
        sudo apt-get install libc++-11-dev libc++abi-11-dev
        ls

    - name: CLANG check
      run: clang++-11 -v

    - name: Build clang
      working-directory: ${{ env.HOME }}
      shell: bash
      run: |
           cmake . -DCMAKE_BUILD_TYPE=Release  
           make
      env:
        CXX: clang++-11
        CC: clang-11         
           
    - name: Benchmark
      working-directory: ${{ env.HOME }}
      shell: bash
      continue-on-error: true
      run: ./benchmark_eswitch