name: clang CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clang 12 and libc++
      id: install_clang_12
      shell: bash
      working-directory: ${{ env.HOME }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 12
        sudo apt-get install libc++-12-dev libc++abi-12-dev
        ls

    - name: CLANG check
      run: clang++ -v

    - name: Build clang
      working-directory: ${{ env.HOME }}
      shell: bash
      run: ./build.sh  
      env:
        CXX: clang++-12
        CC: clang-12         
           
    - name: Benchmark
      working-directory: ${{ env.HOME }}
      shell: bash
      continue-on-error: true
      run: ./build/release/eswitch_benchmark