name: eswitch_v5 CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clang 12 and libc++
      id: install_clang_12
      shell: bash
      working-directory: ${{ env.HOME }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 12
        sudo apt-get install libc++-12-dev libc++abi-12-dev
        ls

    - name: CLANG check
      run: clang++-12 -v


    - name: Install gcc 10
      id: install_gcc_10
      shell: bash
      working-directory: ${{ env.HOME }}
      run: |
        sudo apt-get install -y g++-10
        ls

    - name: GCC check
      run: g++-10 -v
        
    - name: Configure
      shell: cmake -P {0}
      run: |
        set(ENV{CC} ${{ matrix.config.cc }})
        set(ENV{CXX} ${{ matrix.config.cxx }})


    - name: Build clang
      working-directory: ${{ env.HOME }}
      shell: bash
      run: ./build.sh clang++-12           

    - name: Test
      working-directory: ${{ env.HOME }}
      shell: bash
      run: ./build/release/eswitch_tests
           
    - name: Benchmark
      working-directory: ${{ env.HOME }}
      shell: bash
      continue-on-error: true
      run: ./build/release/eswitch_benchmark

    # TODO fix gcc build
    # - name: Build gcc
    #   working-directory: ${{ env.HOME }}
    #   shell: bash
    #   run: ./build.sh g++-10

    # - name: Test
    #   working-directory: ${{ env.HOME }}
    #   shell: bash
    #   run: ./build/release/eswitch_tests
           
    # - name: Benchmark
    #   working-directory: ${{ env.HOME }}
    #   shell: bash
    #   continue-on-error: true
    #   run: ./build/release/eswitch_benchmark