name: gcc CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install gcc 10
      id: install_gcc_10
      shell: bash
      working-directory: ${{ env.HOME }}
      run: |
        sudo apt-get install -y g++-10
        ls

    - name: GCC check
      run: g++-10 -v
        
    - name: Build clang
      working-directory: ${{ env.HOME }}
      shell: bash
      run: |
           cmake . -DCMAKE_BUILD_TYPE=Release  
           make
      env:
        CXX: g++-10
        CC: gcc-10
           
    - name: Benchmark
      working-directory: ${{ env.HOME }}
      shell: bash
      continue-on-error: true
      run: ./eswitch_benchmark